version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ksr_user
      POSTGRES_PASSWORD: ksr_password
      POSTGRES_DB: ksr_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
