export const business = {
  name: "KSR Shipping Services - A Courier Service",
  logoUrl: "/logo.png",
  siteUrl: "https://ksrshipping.com",
  locality: "Begumpet",
  region: "Telangana",
  country: "IN",
  postalCode: "500016",
  geo: {
    latitude: 17.44121770125202,
    longitude: 78.46720187527508,
  },
  address: "Khaja Mansion, beside HDFC ATM, Near Ramalingeswara Temple, Prakash Nagar, Begumpet, Hyderabad, Telangana 500016",
  phone: "+91 99638 14267",
  phoneSecondary: "+91 99120 14267",
  whatsapp: "+91 99638 14267",
  email: "ksrshippingservice@gmail.com",
  googleMapsUrl: "https://maps.app.goo.gl/aKJmfr8GzsbEtgtz7?g_st=ac",
  googleReviewUrl: "https://g.page/r/CdBtDQra-a6oEB0/review",
  hours: "Mon-Sat: 9:00 AM - 9:00 PM, Sun: Closed",
  social: {
    facebook: "",
    instagram: "https://www.instagram.com/ksr_shipping_services?igsh=MWxveW1odmlnMXcxeA==",
    linkedin: "",
    youtube: "",
  },
  seo: {
    defaultTitle: "KSR Shipping Services - Best Courier Services Hyderabad",
    defaultDescription: "Reliable and fast courier services in Hyderabad. 100% Free Pickup & Packing. High-quality food-grade materials used. Affordable domestic and international shipping.",
    keywords: [
      "courier service hyderabad", 
      "international shipping hyderabad",
      "free pickup courier hyderabad",
      "food grade packing courier",
      "affordable international courier",
      "shipping to USA",
      "shipping to UK",
      "shipping to Canada",
      "shipping to Australia",
      "shipping to UAE",
      "shipping to Singapore",
      "shipping to New Zealand",
      "shipping to Europe",
      "domestic courier Telangana",
      "domestic courier Andhra Pradesh",
      "domestic courier Bangalore",
      "domestic courier Chennai",
      "domestic courier Mumbai",
      "domestic courier Delhi"
    ],
  },
  analytics: {
    gaId: "",
  },
  stats: {
    // Every number here is a placeholder until real figures are supplied — render with a visible TODO comment, never invent a number.
    yearsInBusiness: "PLACEHOLDER",
    shipmentsDelivered: "PLACEHOLDER",
    citiesCovered: "PLACEHOLDER",
    averageRating: "PLACEHOLDER",
  },
};
